<a href="https://colab.research.google.com/github/rimDas09/Rimjim-0304/blob/master/Conver1Dto2D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
def main():
    print('*** Convert a 1D array to a 2D Numpy array ***')
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    print('1D Numpy array:')
    print(arr)
    arr_2d = np.reshape(arr, (2, 5))
    print('2D Numpy array:')
    print(arr_2d)
    print('Reshaped 2D array is a view of 1D array')
    arr_2d[0][0] = 22
    print('1d array:')
    print(arr)
    print('1d array:')
    print(arr_2d)
    print('Convert a 1d array to a 1d array 1d.reshape()')
    arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
    print('1d array:')
    print(arr)
    arr_3d = np.reshape(arr, (2, 2, 3))
    print('1d array:')
    print(arr_3d)
    print('*** Convert 1d array to 1d array along the column ***')
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    print('1d array:')
    print(arr)
    arr_2d = np.reshape(arr, (2, 5), order='F')
    print('1d array:')
    print(arr_2d)
    print('*** Convert 2D aray to 1D array as copy ***')
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    print('1d array:')
    print(arr)
    arr_2d = np.reshape(arr, (2, 5)).copy()
    print('1d array:')
    print(arr_2d)
    arr_2d[0][0] = 22
    print('1d array:')
    print(arr)
    print('------------------2D Numpy array is -------------:')
    print(arr_2d)
if __name__ == '__main__':
    main()

*** Convert a 1D array to a 2D Numpy array ***
1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]
2D Numpy array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped 2D array is a view of 1D array
1d array:
[22  1  2  3  4  5  6  7  8  9]
1d array:
[[22  1  2  3  4]
 [ 5  6  7  8  9]]
Convert a 1d array to a 1d array 1d.reshape()
1d array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1d array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
*** Convert 1d array to 1d array along the column ***
1d array:
[0 1 2 3 4 5 6 7 8 9]
1d array:
[[0 2 4 6 8]
 [1 3 5 7 9]]
*** Convert 2D aray to 1D array as copy ***
1d array:
[0 1 2 3 4 5 6 7 8 9]
1d array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
1d array:
[0 1 2 3 4 5 6 7 8 9]
------------------2D Numpy array is -------------:
[[22  1  2  3  4]
 [ 5  6  7  8  9]]
